services:
  web:
    container_name: tdk-sozluk-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Data Source=/AspnetCoreMvcStarter/sqlite-data/tdksozluk.db
      - AdminSeedPassword=${ADMIN_PASSWORD}
    volumes:
      - ./sqlite-data:/AspnetCoreMvcStarter/sqlite-data
      - ./backups:/AspnetCoreMvcStarter/Backups
      - ./wwwroot/uploads:/AspnetCoreMvcStarter/wwwroot/uploads
    restart: always
