version: '3.9'
services:
  web:
    container_name: tdk-sozluk-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5050:80'
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=tdksozluk;Username=tdkadmin;Password=${DB_PASSWORD}
      - AdminSeedPassword=${ADMIN_PASSWORD}
    volumes:
      - ./data:/app/data
      - ./wwwroot/uploads:/app/wwwroot/uploads
    restart: always
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    container_name: tdk-sozluk-db
    environment:
      POSTGRES_USER: tdkadmin
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: tdksozluk
    ports:
      - '5432:5432'
    volumes:
      - ./db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tdkadmin -d tdksozluk"]
      interval: 5s
      timeout: 5s
      retries: 5
